name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - macos-latest
          - windows-latest
      create_release:
        description: 'Create a new release'
        required: false
        default: true
        type: boolean

jobs:
  create-release:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.create_release == true)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.run_number) }}
          name: ${{ github.event_name == 'push' && format('Dance {0}', github.ref_name) || format('Dance v{0}', github.run_number) }}
          body: 'See the assets to download and install this version.'
          draft: false
          prerelease: false

  release:
    needs: [create-release]
    if: always() && (needs.create-release.result == 'success' || needs.create-release.result == 'skipped')
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ github.event_name == 'workflow_dispatch' && inputs.platform != 'all' && fromJSON(format('["{0}"]', inputs.platform)) || fromJSON('["macos-latest", "windows-latest"]') }}

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Install dependencies (Windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install frontend dependencies
        run: pnpm install

      - name: Verify Aptabase Key is set
        run: |
          if [ -n "${{ secrets.APTABASE_APP_KEY }}" ]; then
            echo "✓ APTABASE_APP_KEY is configured in GitHub Secrets"
            echo "Key prefix: $(echo "${{ secrets.APTABASE_APP_KEY }}" | cut -c1-5)..."
          else
            echo "✗ APTABASE_APP_KEY is not configured in GitHub Secrets"
          fi
        shell: bash

      - name: Build the app (macOS Apple Silicon)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tagName: ${{ needs.create-release.result == 'skipped' && format('v{0}', github.run_number) || '' }}
          releaseName: ${{ needs.create-release.result == 'skipped' && format('Dance Build v{0}', github.run_number) || '' }}
          releaseBody: ${{ needs.create-release.result == 'skipped' && 'Manual build artifacts' || '' }}
          releaseDraft: ${{ needs.create-release.result == 'skipped' && true || false }}
          args: --target aarch64-apple-darwin

      - name: Build the app (macOS Intel)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tagName: ${{ needs.create-release.result == 'skipped' && format('v{0}', github.run_number) || '' }}
          releaseName: ${{ needs.create-release.result == 'skipped' && format('Dance Build v{0}', github.run_number) || '' }}
          releaseBody: ${{ needs.create-release.result == 'skipped' && 'Manual build artifacts' || '' }}
          releaseDraft: ${{ needs.create-release.result == 'skipped' && true || false }}
          args: --target x86_64-apple-darwin

      - name: Build the app (Windows)
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tagName: ${{ needs.create-release.result == 'skipped' && format('v{0}', github.run_number) || '' }}
          releaseName: ${{ needs.create-release.result == 'skipped' && format('Dance Build v{0}', github.run_number) || '' }}
          releaseBody: ${{ needs.create-release.result == 'skipped' && 'Manual build artifacts' || '' }}
          releaseDraft: ${{ needs.create-release.result == 'skipped' && true || false }}
          args: --target x86_64-pc-windows-msvc